# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_cluster_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine',
            name='subregion',
        ),
        migrations.AddField(
            model_name='wine',
            name='abv',
            field=models.DecimalField(decimal_places=2, default=14, max_digits=4),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(20, '20'), (19, '19'), (18, '18'), (17, '17'), (16, '16'), (15, 'I would buy (again)'), (14, '14'), (13, '13'), (12, '12'), (11, '11'), (10, 'Average, considering cost'), (9, '9'), (8, '8'), (7, '7'), (6, '6'), (5, 'Not good at this price'), (4, '4'), (3, '3'), (2, '2'), (1, '1')], default=10),
        ),
    ]
