# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20161014_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.CharField(max_length=999),
        ),
    ]
