# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload_handling', '0002_auto_20161012_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wineimage',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wineimages', to='reviews.Review'),
        ),
        migrations.AlterField(
            model_name='wineimage',
            name='wine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wineimages', to='reviews.Wine'),
        ),
    ]
