# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 05:27
from __future__ import unicode_literals

from django.db import migrations, models
import winearb.upload_handling.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_handling', '0003_auto_20161013_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='shot',
            field=models.ImageField(upload_to=winearb.upload_handling.models.image_upload_path, validators=[winearb.upload_handling.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='wineimage',
            name='shot',
            field=models.ImageField(upload_to=winearb.upload_handling.models.image_upload_path, validators=[winearb.upload_handling.models.validate_image_size]),
        ),
    ]
