# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 22:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_remove_article_image'),
        ('upload_handling', '0003_articleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleimage',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articleimages', to='articles.Article'),
        ),
    ]
