# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 23:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_handling', '0004_articleimage_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleimage',
            name='article',
        ),
    ]
