# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 01:30
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models
import winearb.upload_handling.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=255)),
                ('sub_title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=b'', verbose_name=winearb.upload_handling.models.ArticleImage)),
                ('date', models.CharField(max_length=40)),
                ('text', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'Article',
            },
        ),
    ]
