# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='Robert Bradley', max_length=255),
        ),
    ]
