# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload_handling', '0005_remove_articleimage_article'),
        ('articles', '0004_remove_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='upload_handling.ArticleImage'),
            preserve_default=False,
        ),
    ]
